# Configuration for the Workflow
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: data/raw/sample_data.zip
  target_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  source_path: artifacts/data_ingestion/sample_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_labeling:
  root_dir: artifacts/data_labeling
  source_path: artifacts/data_ingestion/sample_data.csv
  target_dir: artifacts/data_labeling

data_transformation:
  root_dir: artifacts/data_transformation
  source_path: artifacts/data_labeling/sample_data.csv
  cleaned_data_path: artifacts/data_transformation/clean_sample_data.csv
  transformed_data_path: artifacts/data_transformation/transformed_sample_data.csv
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

model_predictor:
  root_dir: models
  model_path: models/model.joblib